spring:
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

logging.:
    level.: INFO
    level.root: INFO
    level.ROOT: INFO
server:
    port: 80

    